name = "network-monitoring-dashboard"
type = "javascript"
account_id = "1e8a3f9b566b39698c41d0f30b91204f"
workers_dev = true
route = ""
zone_id = ""

[site]
bucket = "./dist"
entry-point = "workers-site" 